Molecules message
shinonome-inc/shunya-Shunya-Kudo-frontend-basic-last-assignment pull request #2
Opened 2022-08-19 15:23 UTC by ssshun3

## セルフチェック
- [o ] お手本通りの見た目であるか　ホバー時の挙動、レスポンシブ対応など要確認
- [ o] ブランチ名、ファイル名、クラス名、インデントなど、コーディング規則を逸脱していないか
- [ o] 記述の重複はないか

リンク
[](https://62f78284ff92635ba90a59bc-uxbihbyivn.chromatic.com/?path=/story/molecules-message--message)

2022-08-21 13:40 UTC, Hasegawa62 reviewed
全体を通して、paddingの使い方をつかめていないように見えます。
paddingの使い方、marginとの使い分けなどを調べてみると良いと思います！

また、デベロッパーツールを見て、効いていない数値はないか確認ると上手く指定できないところも減らせると思います！

2022-08-21 13:40 UTC, Hasegawa62 commented on src/components/molecules/message/message.html
> +  <div class="message">説明テキスト</div>
並列的な役割を持つものでしたら同じタグとクラスで良いのですが、
「タイトルテキスト」と「説明テキスト」は異なる内容を持つものなので
タグ，クラスともにそれぞれ別の物を使いましょう！

2022-08-21 13:40 UTC, Hasegawa62 commented on src/components/molecules/message/message.scss
> +  width: 327px;
この後課題を進めていくと、このmessageに長いテキストを入れていくことになります。
よって、今はwidthの指定は必要ないです！
他の場所も同様に消してしまってください！

2022-08-21 13:40 UTC, Hasegawa62 commented on src/components/molecules/message/message.scss
> +  .message:nth-of-type(1) {
3行目にも同じ1行が書いてあります！

2022-08-21 13:40 UTC, Hasegawa62 commented on src/components/molecules/message/message.scss
> +    font-weight: 400;
font-weightは400が初期値になっているのでここでの記述は必要ないです！

2022-08-21 13:40 UTC, Hasegawa62 commented on src/components/molecules/message/message.scss
> +      padding: 0px, 0px, 6px, 0px;
「,」必要ないです！

2022-08-22 14:44 UTC, minezaki-mutsuki commented on src/components/molecules/message/message.scss
> +.message-f {
文字数が増えた時に画面いっぱいに文字が満たされてしまうのでpaddingがほしいです。
また、文字が中央によってないです。
![スクリーンショット (196)](https://user-images.githubusercontent.com/83950556/185949134-ca11f680-9e1a-45a7-bc5c-fbebf9bc0e6f.png)

2022-08-22 14:44 UTC, minezaki-mutsuki commented on src/components/molecules/message/message.scss
> +  height: 204px;
基本的にwidthやheightを（絶対値で）指定することはしないです。これを指定しないことで文字数の変化や画面幅の変化に柔軟に見た目が変化してくれます。

2022-08-22 14:44 UTC, minezaki-mutsuki commented on src/components/molecules/message/message.scss
> +    font-family: $fontfamily-mincho;
ここはゴシック体です

2022-08-25 08:55 UTC, minezaki-mutsuki commented on src/components/molecules/message/message.html
> +  <h1 class="message-title">タイトルテキスト</h1>
h1タグはページ1つにつき1回までの使用が望ましいです。このような使い回しが想定されるコンポーネントには使いません。h2がいいかなと思います。

2022-08-25 08:55 UTC, minezaki-mutsuki commented on src/components/molecules/message/message.scss
> +  .message-text {
pタグにはデフォルトでmargin-bottomがついているので消しましょう

2022-08-27 07:57 UTC, higashiji2000 reviewed
ほとんどいい感じです。これは二次レビュー扱いにして、次回の提出の際は @higashiji にメンションを飛ばしてください。

2022-08-27 07:57 UTC, higashiji2000 commented on src/components/molecules/message/message.scss
> +  align-items: center;
![image](https://user-images.githubusercontent.com/83479175/187020751-121d1ee6-d34a-4a59-b4de-7ffe56211612.png)
text-align で中央寄せができているので、4~7行目はなくても大丈夫です！

2022-08-27 07:57 UTC, higashiji2000 commented on src/components/molecules/message/message.scss
> +}
メディアクエリを入れ子にした方がスッキリかける場合はどんどんしていきましょう。
以下は[課題ページ](https://shinonome.io/frontend-basic/lastAssignment/storybook_sass/)の説明です。

---
scss ではメディアクエリも入れ子にできます。
```
.example {
  hoge: fuga;

  @media (max-width: $breakpoint-md) {
    hoge: fugafuga;
  }
}
```
このように書いた場合
```
.example {
  hoge: fuga;
}

@media (max-width: 768px) {
  .example {
    hoge: fugafuga;
  }
}
```
このように変換されます。

2022-08-27 08:30 UTC, higashiji2000 requested changes

2022-08-27 08:30 UTC, higashiji2000 commented on src/components/molecules/message/message.scss
> +}
htmlの入れ子構造をscssにも反映するようお願いします。
今回は .molecules-message が .message-title と .message-text の親なので、

```
.molecules-message {
  // いろいろ
  .message-title {
    // いろいろ
    }
  .message-text {
    // いろいろ
    }
}
```

という感じで書くようにお願いします。こうすることで影響範囲が狭まり、不要な副作用の防止につながります。

2022-08-27 08:42 UTC, higashiji2000 approved these changes
LGTMです 🧄

2022-08-27 09:10 UTC, merged